formspree_form_id: formspree_form_id
name: Vernl Blog
title: Vernl news, product updates, and industry insights
description: Get the latest Vernl news, product updates, and industry insights
  delivered straight to you.
tags:
  - blog
  - Vernl
  - news
  - product updates
  - industry insights
show_hero: true
paginate: 10
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
disqus_username: disqus_username
